
import React from 'react';
import { ArrowLeftIcon } from './icons/ArrowLeftIcon';
import { SparklesIcon } from './icons/SparklesIcon';
import { SuggestedRecipe } from '../types';

interface RecipeSuggestionsScreenProps {
  onClose: () => void;
  isLoading: boolean;
  suggestions: SuggestedRecipe[];
}

const LoadingSkeleton: React.FC = () => (
    <div className="bg-white dark:bg-gray-800 rounded-xl p-4 animate-pulse">
        <div className="h-6 bg-gray-200 dark:bg-gray-700 rounded w-3/4 mb-3"></div>
        <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-full mb-4"></div>
        <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-5/6 mb-4"></div>
        
        <div className="h-5 bg-gray-200 dark:bg-gray-700 rounded w-1/4 mb-2 mt-4"></div>
        <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-full mb-2"></div>
        <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-full mb-2"></div>
    </div>
)

const RecipeSuggestionsScreen: React.FC<RecipeSuggestionsScreenProps> = ({ 
    onClose, isLoading, suggestions
}) => {
  return (
    <div className="absolute inset-0 bg-gray-50 dark:bg-gray-950 z-30 flex flex-col animate-slide-in">
      <header className="flex items-center p-4 border-b border-gray-200 dark:border-gray-800 sticky top-0 bg-gray-50/80 dark:bg-gray-950/80 backdrop-blur-lg">
        <button onClick={onClose} className="p-2 -ml-2 mr-2">
          <ArrowLeftIcon className="w-6 h-6 text-gray-600 dark:text-gray-300" />
        </button>
        <h1 className="text-lg font-semibold text-gray-800 dark:text-gray-100">AI Recipe Ideas</h1>
      </header>

      <div className="flex-grow p-4 overflow-y-auto">
        <div className="bg-violet-50 dark:bg-violet-900/20 border border-violet-200 dark:border-violet-800 rounded-xl p-4 mb-6 flex items-start gap-3">
            <SparklesIcon className="w-6 h-6 text-violet-600 dark:text-violet-400 flex-shrink-0 mt-1" />
            <p className="text-violet-800 dark:text-violet-200 text-sm">Here are a few ideas generated by AI based on what's in your pantry. Results may vary and some additional common ingredients might be needed.</p>
        </div>
        
        {isLoading ? (
            <div className="space-y-4">
                <LoadingSkeleton />
                <LoadingSkeleton />
            </div>
        ) : (
            <div className="space-y-4">
                {suggestions.map((recipe, index) => (
                    <div key={index} className="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm">
                        <h2 className="text-xl font-bold text-gray-800 dark:text-white mb-2">{recipe.recipeName}</h2>
                        <p className="text-gray-600 dark:text-gray-300 mb-4">{recipe.description}</p>
                        
                        <div>
                            <h3 className="font-semibold text-gray-700 dark:text-gray-200 mb-2">Ingredients:</h3>
                            <ul className="list-disc list-inside text-gray-600 dark:text-gray-300 space-y-1 text-sm">
                                {recipe.ingredients.map((ing, i) => <li key={i}>{ing}</li>)}
                            </ul>
                        </div>
                        
                         <div className="mt-4">
                            <h3 className="font-semibold text-gray-700 dark:text-gray-200 mb-2">Instructions:</h3>
                            <ol className="list-decimal list-inside text-gray-600 dark:text-gray-300 space-y-2 text-sm">
                                {recipe.instructions.map((step, i) => <li key={i}>{step}</li>)}
                            </ol>
                        </div>
                    </div>
                ))}
            </div>
        )}
      </div>
       <style>{`
            @keyframes slide-in {
                from { transform: translateX(100%); }
                to { transform: translateX(0); }
            }
            .animate-slide-in {
                animation: slide-in 0.3s ease-out;
            }
        `}</style>
    </div>
  );
};

export default RecipeSuggestionsScreen;
